package com.puluo.enumeration;

public enum WechatButtonType {
	INFO1, INFO2, INFO3, INFO4,INFO5,
	CURRICULUM,PROMOTION,INTRODUCTION, 
	HOTTEST, REGISTER, ORDERS, DOWNLOAD, 
	SERVICE,SUBSCRIBE,UNSUBSCRIBE
}
