package com.unuotech.config

/**
 * 每个颜色的序号与数据库的商品属性绑定， ！非常！重要，任何情况下不可以改变！
 */
object Colors extends Enumeration {
  type Colors = Value
  val UNKNOWN = Value(0,"其它")
  val BLACK = Value(1,"黑色")
  val DIMGRAY = Value(2,"昏灰")
  val GRAY = Value(3,"灰色")
  val DARK_GRAY = Value(4,"暗灰")
  val SILVER = Value(5,"银色")
  val LIGHT_GRAY = Value(6,"亮灰色")
  val WHITE = Value(7,"白色")
  val SNOW = Value(8,"雪色")
  val BROWN = Value(9,"褐色")
  val MAROON = Value(10,"栗色")
  val DARK_RED = Value(11,"暗红")
  val STRONG_RED = Value(12,"鲜红")
  val KHAKI = Value(13,"卡其色")
  val WHEAT = Value(14,"小麦色")
  val PEACH = Value(15,"桃色")
  val ORANGE = Value(16,"橙色")
  val GOLDENROD = Value(17,"金菊色")
  val COFFEE = Value(18,"咖啡色")
  val GOLDEN = Value(19,"金色")
  val BEIGE = Value(20,"米黄色")
  val YELLOW = Value(21,"黄色")
  val YELLOW_GREEN = Value(22,"黄绿")
  val GRASS_GREEN = Value(23,"草绿")
  val GREEN = Value(24,"绿色")
  val CYAN_BLUE = Value(25,"青蓝")
  val AQUA_BLUE = Value(26,"水蓝")
  val BABY_BLUE = Value(27,"浅蓝")
  val PEACOCK_BLUE = Value(28,"孔雀蓝")
  val SKY_BLUE = Value(29,"天蓝")
  val CERULEAN_BLUE = Value(30,"蔚蓝")
  val ROYAL_BLUE = Value(31,"品蓝")
  val BLUE = Value(32,"蓝色")
  val MEDIUM_PURPLE = Value(33,"中紫红")
  val BLUE_VIOLET = Value(34,"蓝紫")
  val VIOLET = Value(35,"紫罗兰色")
  val PURPLE = Value(36,"紫色")
  val FUCHSIA = Value(37,"品红")
  val ROSE = Value(38,"玫瑰红")
  val PINK = Value(39,"粉红")
  /*val JASMINE = Value(,"茉莉黄")
  val AMBER = Value(,"琥珀色")
  val CORNSILK = Value(,"玉米丝色")
  val CHROME_YELLOW = Value(,"铬黄")*/

  /*val LEMON_CHIFFON = Value(,"柠檬绸色")
  val LIGHT_KHAKI = Value(,"亮卡其色")
  val PALE_GOLDENROD = Value(,"灰金菊色")
  val DARK_KHAKI = Value(,"暗卡其色")
  val MIMOSA = Value(,"含羞草黄")
  val CREAM = Value(,"奶油色")
  val IVORY = Value(,"象牙色")*/

  /*val LIGHT_YELLOW = Value(,"亮黄")
  val LIGHT_GOLDENROD_YELLOW = Value(,"亮金菊黄")
  val CHAMPAGNE_YELLOW = Value(,"香槟黄")
  val MUSTARD = Value(,"芥末黄")
  val MOON_YELLOW = Value(,"月黄")
  val OLIVE = Value(,"橄榄色")
  val CANARY_YELLOW = Value(,"鲜黄")*/

  /*val MOSS_GREEN = Value(,"苔藓绿")
  val LIGHT_LIME = Value(,"亮柠檬绿")
  val OLIVE_DRAB = Value(,"橄榄军服绿")*/

  //val DARK_OLIVE_GREEN = Value(,"暗橄榄绿")
  //val APPLE_GREEN = Value(,"苹果绿")
  //val GREEN_YELLOW = Value(,"绿黄")
  //val LAWN_GREEN = Value(,"草坪绿")
  //val CHARTREUSE = Value(,"查特酒绿")
  //val FOLIAGE_GREEN = Value(,"叶绿")
  //val FRESH_LEAVES = Value(,"嫩绿")
  //val BRIGHT_GREEN = Value(,"明绿")
  //val COBALT_GREEN = Value(,"钴绿")
  //val HONEYDEW = Value(,"蜜瓜绿")
  //val DARK_SEA_GREEN = Value(,"暗海绿")
  //val LIGHT_GREEN = Value(,"亮绿")
  //val PALE_GREEN = Value(,"灰绿")
  //val IVY_GREEN = Value(,"常春藤绿")
  //val FOREST_GREEN = Value(,"森林绿")
  //val LIME_GREEN = Value(,"柠檬绿")
  //val DARK_GREEN = Value(,"暗绿")
  /*val LIME = Value(,"鲜绿色")
  val MALACHITE = Value(,"孔雀石绿")
  val MINT = Value(,"薄荷绿")
  val CELADON_GREEN = Value(,"青瓷绿")
  val EMERALD = Value(,"碧绿")
  val TURQUOISE_GREEN = Value(,"绿松石绿")
  val VERIDIAN = Value(,"铬绿")
  val HORIZON_BLUE = Value(,"苍色")
  val SEA_GREEN = Value(,"海绿")
  val MEDIUM_SEA_GREEN = Value(,"中海绿")
  val MINT_CREAM = Value(,"薄荷奶油色")
  val SPRING_GREEN = Value(,"春绿")
  val PEACOCK_GREEN = Value(,"孔雀绿")
  val MEDIUM_SPRING_GREEN = Value(,"中春绿色")
  val MEDIUM_AQUAMARINE = Value(,"中碧蓝色")
  val AQUAMARINE = Value(,"碧蓝色")*/
  /*val TURQUOISE_BLUE = Value(,"绿松石蓝")
  val TURQUOISE = Value(,"绿松石色")
  val LIGHT_SEA_GREEN = Value(,"亮海绿")
  val MEDIUM_TURQUOISE = Value(,"中绿松石色")
  val LIGHT_CYAN = Value(,"亮青")*/

  /*val PALE_TURQUOISE = Value(,"灰绿松石色")
  val DARK_SLATE_GRAY = Value(,"暗岩灰")
  val TEAL = Value(,"凫绿")
  val DARK_CYAN = Value(,"暗青")
  val CYAN = Value(,"青色")
  val AQUA = Value(,"水色")
  val DARK_TURQUOISE = Value(,"暗绿松石色")
  val CADET_BLUE = Value(,"军服蓝")*/

  /*val POWDER_BLUE = Value(,"婴儿粉蓝")
  val STRONG_BLUE = Value(,"浓蓝")
  val LIGHT_BLUE = Value(,"亮蓝")
  val PALE_BLUE = Value(,"灰蓝")
  val SAXE_BLUE = Value(,"萨克斯蓝")
  val DEEP_SKY_BLUE = Value(,"深天蓝")*/

  /*val LIGHT_SKY_BLUE = Value(,"亮天蓝")
  val MARINE_BLUE = Value(,"水手蓝")
  val PRUSSIAN_BLUE = Value(,"普鲁士蓝")
  val STEEL_BLUE = Value(,"钢青色")
  val ALICE_BLUE = Value(,"爱丽丝蓝")
  val SLATE_GRAY = Value(,"岩灰")
  val LIGHT_SLATE_GRAY = Value(,"亮岩灰")
  val DODGER_BLUE = Value(,"道奇蓝")
  val MINERAL_BLUE = Value(,"矿蓝")
  val AZURE = Value(,"湛蓝")
  val WEDGWOOD_BLUE = Value(,"韦奇伍德瓷蓝")
  val LIGHT_STEEL_BLUE = Value(,"亮钢蓝")
  val COBALT_BLUE = Value(,"钴蓝")
  val PALE_DENIM = Value(,"灰丁宁蓝")
  val CORNFLOWER_BLUE = Value(,"矢车菊蓝")
  val SALVIA_BLUE = Value(,"鼠尾草蓝")
  val DARK_POWDER_BLUE = Value(,"暗婴儿粉蓝")
  val SAPPHIRE = Value(,"蓝宝石色")
  val INTERNATIONAL_KLEIN_BLUE = Value(,"国际奇连蓝")*/

  /* val DARK_MINERAL_BLUE = Value(,"暗矿蓝")
  val ULTRAMARINE = Value(,"极浓海蓝")
  val LAPIS_LAZULI = Value(,"天青石蓝")
  val GHOST_WHITE = Value(,"幽灵白")
  val LAVENDER = Value(,"薰衣草紫")
  val PERIWINKLE = Value(,"长春花色")
  val MIDNIGHT_BLUE = Value(,"午夜蓝")
  val NAVY_BLUE = Value(,"藏青")
  val DARK_BLUE = Value(,"暗蓝")
  val MEDIUM_BLUE = Value(,"中蓝")*/

  /*val WISTERIA = Value(,"紫藤色")
  val DARK_SLATE_BLUE = Value(,"暗岩蓝")
  val SLATE_BLUE = Value(,"岩蓝")
  val MEDIUM_SLATE_BLUE = Value(,"中岩蓝")
  val MAUVE = Value(,"木槿紫")
  val LILAC = Value(,"紫丁香色")*/

  /*val AMETHYST = Value(,"紫水晶色")
  val GRAYISH_PURPLE = Value(,"浅灰紫红")
  val HELIOTROPE = Value(,"缬草紫")
  val MINERAL_VIOLET = Value(,"矿紫")*/

  /*val INDIGO = Value(,"靛色")
  val DARK_ORCHID = Value(,"暗兰紫")
  val DARK_VIOLET = Value(,"暗紫")
  val PANSY = Value(,"三色堇紫")
  val MALLOW = Value(,"锦葵紫")
  val OPERA_MAUVE = Value(,"优品紫红")
  val MEDIUM_ORCHID = Value(,"中兰紫")
  val PAIL_LILAC = Value(,"淡紫丁香色")
  val THISTLE = Value(,"蓟紫")
  val CLEMATIS = Value(,"铁线莲紫")
  val PLUM = Value(,"梅红色")
  val LIGHT_VIOLET = Value(,"亮紫")*/

  //val DARK_MAGENTA = Value(,"暗洋红")
  //val MAGENTA = Value(,"洋红")

  /*val ORCHID = Value(,"兰紫")
  val PEARL_PINK = Value(,"浅珍珠红")
  val OLD_ROSE = Value(,"陈玫红")
  val ROSE_PINK = Value(,"浅玫瑰红")
  val MEDIUM_VIOLET_RED = Value(,"中青紫红")
  val MAGENTA_ROSE = Value(,"洋玫瑰红")*/

  /*val RUBY = Value(,"红宝石色")
  val CAMELLIA = Value(,"山茶红")
  val DEEP_PINK = Value(,"深粉红")
  val FLAMINGO = Value(,"火鹤红")
  val CORAL_PINK = Value(,"浅珊瑚红")
  val HOT_PINK = Value(,"暖粉红")
  val BURGUNDY = Value(,"勃艮第酒红")
  val SPINEL_RED = Value(,"尖晶石红")
  val CARMINE = Value(,"胭脂红")
  val BABY_PINK = Value(,"浅粉红")
  val CARDINAL_RED = Value(,"枢机红")
  val LAVENDER_BLUSH = Value(,"薰衣草紫红")
  val PALE_VIOLET_RED = Value(,"灰紫红")
  val CERISE = Value(,"樱桃红")
  val SALMON_PINK = Value(,"浅鲑红")
  val CRIMSON = Value(,"绯红")*/
  //val LIGHT_PINK = Value(,"亮粉红")
  //val SHELL_PINK = Value(,"壳黄红")
  //val ALIZARIN_CRIMSON = Value(,"茜红")
  //val GAINSBORO = Value(,"庚斯博罗灰")
  //val WHITE_SMOKE = Value(,"白烟色")
  /*val IRON_GRAY = Value(,"铁灰色")
  val SAND_BEIGE = Value(,"沙棕")
  val ROSY_BROWN = Value(,"玫瑰褐")
  val LIGHT_CORAL = Value(,"亮珊瑚色")
  val INDIAN_RED = Value(,"印度红")*/
  //val FIRE_BRICK = Value(,"耐火砖红")
  //val RED = Value(,"红色")
  /*val PERSIMMON = Value(,"柿子橙")
  val MISTY_ROSE = Value(,"雾玫瑰色")
  val SALMON = Value(,"鲑红")
  val SCARLET = Value(,"腥红")
  val TOMATO = Value(,"蕃茄红")
  val DARK_SALMON = Value(,"暗鲑红")
  val CORAL = Value(,"珊瑚红")
  val ORANGE_RED = Value(,"橙红")
  val LIGHT_SALMON = Value(,"亮鲑红")
  val VERMILION = Value(,"朱红")
  val SIENNA = Value(,"赭黄")
  val TROPICAL_ORANGE = Value(,"热带橙")
  val CAMEL = Value(,"驼色")
  val APRICOT = Value(,"杏黄")
  val COCONUT_BROWN = Value(,"椰褐")
  val SEASHELL = Value(,"海贝色")
  val SADDLE_BROWN = Value(,"鞍褐")
  val CHOCOLATE = Value(,"巧克力色")
  val BURNT_ORANGE = Value(,"燃橙")
  val SUN_ORANGE = Value(,"阳橙")
  val PEACH_PUFF = Value(,"粉扑桃色")
  val SAND_BROWN = Value(,"沙褐")
  val BRONZE = Value(,"古铜色")
  val LINEN = Value(,"亚麻色")
  val HONEY_ORANGE = Value(,"蜜橙")
  val PERU = Value(,"秘鲁色")
  val SEPIA = Value(,"乌贼墨色")
  val OCHER = Value(,"赭色")
  val BISQUE = Value(,"陶坯黄")
  val TANGERINE = Value(,"橘色")
  val DARK_ORANGE = Value(,"暗橙")
  val ANTIQUE_WHITE = Value(,"古董白")
  val TAN = Value(,"日晒色")
  val BURLY_WOOD = Value(,"硬木色")
  val BLANCHED_ALMOND = Value(,"杏仁白")
  val NAVAJO_WHITE = Value(,"那瓦霍白")
  val MARIGOLD = Value(,"万寿菊黄")
  val PAPAYA_WHIP = Value(,"蕃木瓜色")
  val PALE_OCRE = Value(,"灰土色")*/
  //val MOCCASIN = Value(,"鹿皮鞋色")
  //val OLD_LACE = Value(,"旧蕾丝色")
  //val FLORAL_WHITE = Value(,"花卉白")
  //val DARK_GOLDENROD = Value(,"暗金菊色")

  def isColor(c: String): Boolean = try {
    Colors.withName(c)
    true
  } catch {
    case e: Exception => false
  }
  
  def all = values.map(_.toString)
}
